### ISSUE TITLE
User object in the gateway architecture

### ISSUE THREAD

**Issue by Guit** [strongloop/strong-gateway-demo#2]
Hi

I have carefully study this schema : 
![Image of gateway](https://github.com/strongloop/strong-gateway-demo/raw/master/docs/demo.png)

There is a point I don't understand : which server take care of the user ?
As I have understand it's the authorization server (here localhost:3005). But on my resource server (here 3002) I need to know who is my user: for exemple give the note that belong to me, or give me the note that belong to my role. 
Should I share a model between the different server? Especially in our case, we will inherit from the User Model

It's not very clear in my mind how the user exist in the different entity of the architecture...

**Comment by crandmck** [comment]
Questions such as this are more appropriate for the LoopBack group/forum: https://groups.google.com/forum/#!forum/loopbackjs.  Can you please ask your question there instead?

**Comment by Guit** [comment]
ok no problem :)

**Comment by crandmck** [comment]
Thanks!  See https://groups.google.com/forum/#!topic/loopbackjs/BwmH55XbQFE.
